kids_back_homepage:
    path:     /backend
    defaults: { _controller: KidsBackendBundle:Default:index }

kids_front_homepage:
    path:     /front
    defaults: { _controller: KidsFrontBundle:Default:index }
contact:
    path:     /contact
    defaults: { _controller: KidsFrontBundle:Etablissement:contact }
etablissement:
    path:     /etablissements
    defaults: { _controller: KidsFrontBundle:Etablissement:etablissements }
test:
    path:     /
    defaults: { _controller: KidsFrontBundle:Etablissement:index }
acceuil:
    path:     /acceuil
    defaults: { _controller: KidsFrontBundle:Etablissement:acceuil }

publications:
    path:     /publications
    defaults: { _controller: KidsFrontBundle:Publication:afficherpublication }

afficherespaceenfant:
    path:     /afficherespaceenfant
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:afficherespaceenfant }

afficherpublicationdetails:
    path:     /publicationsdetails/{id}
    defaults: { _controller: KidsFrontBundle:Publication:afficherpublicationdetails }

afficherpublicationcategorie:
    path:     /afficherpublicationcategorie/{categoriePublication}
    defaults: { _controller: KidsFrontBundle:Publication:afficherpublicationcategorie }

imprimerpublication:
    path:     /imprimerpublication/{id}
    defaults: { _controller: KidsFrontBundle:Publication:imprimerpublication }

creerpublication:
    path:     /creerpublication
    defaults: { _controller: KidsFrontBundle:Publication:creerpublication }

creerespace:
    path:     /creerespace
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:creerespace }

espacedetails:
    path:     /espacedetails/{id}
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:espacedetails }

creeractivite:
    path:     /creeractivite/{id}
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:creeractivite }

supprimeractivite:
    path:     /supprimeractivite/{id}/{id1}
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:supprimeractivite }

imprimeractivite:
    path:     /imprimeractivite/{id}
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:imprimeractivite }

proposerpublication:
    path:     /proposerpublication
    defaults: { _controller: KidsFrontBundle:Publication:proposerpublication }