kids_front_homepage:
    path:     /front
    defaults: { _controller: KidsFrontBundle:Default:index }
espace_prestataire:
    path: /espacePrestataire
    defaults: { _controller: KidsFrontBundle:Etablissement:espacePrestataire}
espace_parent:
    path: /espaceParent
    defaults: { _controller: KidsFrontBundle:Parent:espaceParent}
contact:
    path:     /contact
    defaults: { _controller: KidsFrontBundle:AcceuilContact:contact }
test:
    path:     /
    defaults: { _controller: KidsFrontBundle:Etablissement:index }

services:
    path:     /services
    defaults: { _controller: KidsFrontBundle:Services:services }

afficherServiceFront:
    path:     /afficherServiceFront
    defaults: { _controller: KidsFrontBundle:Services:afficherServiceFront}

publications:
    path:     /publications
    defaults: { _controller: KidsFrontBundle:Publication:afficherpublication }

afficherespaceenfant:
    path:     /afficherespaceenfant
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:afficherespaceenfant }

afficherpublicationdetails:
    path:     /publicationsdetails/{id}
    defaults: { _controller: KidsFrontBundle:Publication:afficherpublicationdetails }
ajouterEtablissement:
    path: /ajouterEtablissement
    defaults: { _controller: KidsFrontBundle:Etablissement:ajouterEtablissement }
ajouterEnseignant:
    path: /ajouterEnseignant
    defaults: { _controller: KidsFrontBundle:Enseignant:ajouterEnseignant }
afficherprof:
    path: /afficherprof
    defaults: { _controller: KidsFrontBundle:Enseignant:afficherprof }
afficherdetailprof:
    path: /afficherdetailprof/id/{id}
    defaults: { _controller: KidsFrontBundle:Enseignant:afficherdetailprof }

supprimerfavorisparid:
    path: /supprimerfavorisparid/id/{id}
    defaults: { _controller: KidsFrontBundle:Favoris:supprimerfavorisparid}

modifierenseignantbyid:
    path: /modifierenseignantbyid/id/{id}
    defaults: { _controller: KidsFrontBundle:Enseignant:modifierenseignantbyid }

supprimerenseignantbyid:
    path: /supprimerenseignantbyid/id/{id}
    defaults: { _controller: KidsFrontBundle:Enseignant:supprimersenseignantparid }
ajouterGallerieImage:
    path: /ajouterGallerieImage
    defaults: { _controller: KidsFrontBundle:Gallerie:ajouterGallerieImage}
affichergallerie:
    path: /affichergallerie
    defaults: { _controller: KidsFrontBundle:Gallerie:affichergallerie}
afficherEtabPrestataireInfo:
    path: /afficherEtabPrestataireInfo
    defaults: { _controller: KidsFrontBundle:Etablissement:afficherEtabPrestataireInfo}
afficherEtabById:
    path: /afficherEtabById/id/{id}
    defaults: { _controller: KidsFrontBundle:Etablissement:afficherEtabById}

modifieretablissement:
    path: /modifieretablissement
    defaults: { _controller: KidsFrontBundle:Etablissement:modifieretablissement}

supprimeretablissementparid:
    path: /supprimeretablissementparid/id/{id}
    defaults: { _controller: KidsFrontBundle:Etablissement:supprimeretablissementparid}
afficherprofpourmodifier:
    path: /afficherprofpourmodifier
    defaults: { _controller: KidsFrontBundle:Enseignant:afficherprofpourmodifier}

afficherprofpoursupprimer:
    path: /afficherprofpoursupprimer
    defaults: { _controller: KidsFrontBundle:Enseignant:afficherprofpoursupprimer}

afficherimagepourmodifier:
    path : /afficherimagepourmodifier
    defaults: { _controller: KidsFrontBundle:Gallerie:afficherimagepourmodifier}

afficherimagepoursupprimer:
    path : /afficherimagepoursupprimer
    defaults: { _controller: KidsFrontBundle:Gallerie:afficherimagepoursupprimer}

modifierimagebyid:
    path: /modifierimagebyid/id/{id}
    defaults: { _controller: KidsFrontBundle:Gallerie:modifierimagebyid}

supprimerimagebyid:
    path: /supprimerimagebyid/id/{id}
    defaults: { _controller: KidsFrontBundle:Gallerie:supprimerimageparid}

afficherConfimationApresCreationEtab:
    path: /afficherConfimationApresCreationEtab
    defaults: { _controller: KidsFrontBundle:Etablissement:afficherConfimationApresCreationEtab}

getAllFavoris:
    path: /getAllFavoris
    defaults:  { _controller: KidsFrontBundle:Favoris:getAllFavorisByUser}

afficherEtabByParent:
    path: /afficherEtabByParent
    defaults:  { _controller: KidsFrontBundle:Parent:afficherEtabParent}
ajouterfavoris:
    path: /ajouterfavoris/id/{id}
    defaults: { _controller: KidsFrontBundle:Favoris:ajouterfavoris}
send_notification:
    path: /send-notification
    defaults: { _controller: KidsBackendBundle:Admin:sendNotification}

getNotificationsAction:
    path: /getNotifications
    defaults: { _controller: KidsBackendBundle:Admin:getNotifications}
notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    type: annotation


afficherpublicationcategorie:
    path:     /afficherpublicationcategorie/{categoriePublication}
    defaults: { _controller: KidsFrontBundle:Publication:afficherpublicationcategorie }

imprimerpublication:
    path:     /imprimerpublication/{id}
    defaults: { _controller: KidsFrontBundle:Publication:imprimerpublication }
afficheServ:
    path:     /afficheServ
    defaults: { _controller: KidsFrontBundle:Services:afficheServFront}

detailServiceFront:
    path:     /detail/{id}
    defaults: { _controller: KidsFrontBundle:Services:detailServiceFront}
search:
    path:     /search
    defaults: { _controller: KidsFrontBundle:Services:search}

tempserv:
    path:     /tempserv
    defaults: { _controller: KidsFrontBundle:Services:tempserv}

detailServiceFront2:
    path:     /detail2/{id}
    defaults: { _controller: KidsFrontBundle:Services:detailServiceFront}

recherche:
    path:     /recherche
    defaults: { _controller: KidsFrontBundle:Services:recherche}

creerespace:
    path:     /creerespace
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:creerespace }

espacedetails:
    path:     /espacedetails/{id}
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:espacedetails }

creeractivite:
    path:     /creeractivite/{id}
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:creeractivite }

supprimeractivite:
    path:     /supprimeractivite/{id}/{id1}
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:supprimeractivite }

imprimeractivite:
    path:     /imprimeractivite/{id}
    defaults: { _controller: KidsFrontBundle:EspaceEnfant:imprimeractivite }
template:
    path: /template
    defaults: { _controller: KidsFrontBundle:Default:template}


api_mobile_get_all_etablissement:
    path: /getAllEtablissement
    defaults: { _controller: KidsFrontBundle:EtablissementMobile:allEtab}
api_mobile_get_all_users:
    path: /getAllUsers
    defaults: { _controller: KidsFrontBundle:EtablissementMobile:allUsers}
api_mobile_get_all_favoris_for_user:
    path: /allUserFavoris/userid/{idUser}
    defaults: { _controller: KidsFrontBundle:EtablissementMobile:allUserFavoris}
api_mobile_update_etablissement:
    path: /updateEtab
    defaults: { _controller: KidsFrontBundle:EtablissementMobile:updateEtab}