kids_back_homepage:
    path:     /backend
    defaults: { _controller: KidsBackendBundle:Default:index }

kids_front_homepage:
    path:     /front
    defaults: { _controller: KidsFrontBundle:Default:index }
contact:
    path:     /contact
    defaults: { _controller: KidsFrontBundle:Etablissement:contact }
etablissement:
    path:     /etablissements
    defaults: { _controller: KidsFrontBundle:Etablissement:etablissements }
test:
    path:     /
    defaults: { _controller: KidsFrontBundle:Etablissement:index }
acceuil:
    path:     /acceuil
    defaults: { _controller: KidsFrontBundle:Etablissement:acceuil }
ajouterEtablissement1:
    path: /ajouterEtablissementch1
    defaults: { _controller: KidsFrontBundle:Etablissement:ajouterEtablissement1 }
ajouterEnseignant:
    path: /ajouterEnseignant
    defaults: { _controller: KidsFrontBundle:Etablissement:ajouterEnseignant }
ajouterEtablissement3:
    path: /ajouterEtablissementch3
    defaults: { _controller: KidsFrontBundle:Etablissement:ajouterEtablissement3 }
afficherprof:
    path: /afficherprof
    defaults: { _controller: KidsFrontBundle:Etablissement:afficherprof }
afficherdetailprof:
    path: /afficherdetailprof
    defaults: { _controller: KidsFrontBundle:Etablissement:afficherdetailprof }


