kids_back_homepage:
    path:     /backend
    defaults: { _controller: KidsBackendBundle:Default:index }

kids_front_homepage:
    path:     /front
    defaults: { _controller: KidsFrontBundle:Default:index }
contact:
    path:     /contact
    defaults: { _controller: KidsFrontBundle:Etablissement:contact }
etablissement:
    path:     /etablissements
    defaults: { _controller: KidsFrontBundle:Etablissement:etablissements }
test:
    path:     /
    defaults: { _controller: KidsFrontBundle:Etablissement:index }
acceuil:
    path:     /acceuil
    defaults: { _controller: KidsFrontBundle:Etablissement:acceuil }


ProduitAfficherFront:
        path:     /ProduitAfficherFront
        defaults: { _controller: KidsFrontBundle:Produitfront:ProduitAfficherFront}


detailProduitFront:
        path:     /detailProduitFront/{id}
        defaults: { _controller: KidsFrontBundle:Produitfront:detailProduitFront}

recherche:
        path:     /recherche
        defaults: { _controller: KidsFrontBundle:Produitfront:recherche}

CategorieProduit:
        path:     /CategorieProduit
        defaults: { _controller: KidsFrontBundle:Produitfront:CategorieProduit}
afficherProduitjson:
    path:     /afficherProduitjson
    defaults: { _controller: KidsFrontBundle:Produitfront:afficherProduitjsonFront}
ajoutProduitjson:
    path:     /ajoutProduitjson
    defaults: { _controller: KidsFrontBundle:Produitfront:ajoutProduitjson}
afficherCategoriejson:
    path:     /afficherCategoriejson
    defaults: { _controller: KidsFrontBundle:Produitfront:afficherCategoriejsonFront}

ProduitParCategorie:
    path:     /{id}/ProduitParCategorie
    defaults: { _controller: KidsFrontBundle:Produitfront:produitParCategorie}