kids_back_homepage:
    path:     /back
    defaults: { _controller: KidsBackendBundle:Default:index }

kids_front_homepage:
    path:     /front
    defaults: { _controller: KidsFrontBundle:Default:index }
contact:
    path:     /contact
    defaults: { _controller: KidsFrontBundle:Etablissement:contact }
etablissement:
    path:     /etablissements
    defaults: { _controller: KidsFrontBundle:Etablissement:etablissements }
test:
    path:     /
    defaults: { _controller: KidsFrontBundle:Etablissement:index }
acceuil:
    path:     /acceuil
    defaults: { _controller: KidsFrontBundle:Etablissement:acceuil }

afficheclubsfront:
    path:     /affiche
    defaults: { _controller: KidsFrontBundle:Clubs:afficheclubsfront }
map:
    path:     /map/{id}
    defaults: { _controller: KidsFrontBundle:Clubs:map }
