kids_back_homepage:
    path:     /back
    defaults: { _controller: KidsBackendBundle:Default:index }

kids_front_homepage:
    path:     /front
    defaults: { _controller: KidsFrontBundle:Default:index }
contact:
    path:     /contact
    defaults: { _controller: KidsFrontBundle:Etablissement:contact }
etablissement:
    path:     /etablissements
    defaults: { _controller: KidsFrontBundle:Etablissement:etablissements }
test:
    path:     /
    defaults: { _controller: KidsFrontBundle:Etablissement:index }
acceuil:
    path:     /acceuil
    defaults: { _controller: KidsFrontBundle:Etablissement:acceuil }
services:
    path:     /services
    defaults: { _controller: KidsFrontBundle:Services:services }

afficherServiceFront:
    path:     /afficherServiceFront
    defaults: { _controller: KidsFrontBundle:Services:afficherServiceFront}

afficheServ:
    path:     /afficheServ
    defaults: { _controller: KidsFrontBundle:Services:afficheServFront}

detailServiceFront:
    path:     /detail/{id}
    defaults: { _controller: KidsFrontBundle:Services:detailServiceFront}
search:
    path:     /search
    defaults: { _controller: KidsFrontBundle:Services:search}

tempserv:
    path:     /tempserv
    defaults: { _controller: KidsFrontBundle:Services:tempserv}

detailServiceFront2:
    path:     /detail2/{id}
    defaults: { _controller: KidsFrontBundle:Services:detailServiceFront}

recherche:
    path:     /recherche
    defaults: { _controller: KidsFrontBundle:Services:recherche}
ajoutrendezvous:
    path:     /ajoutrendezvous
    defaults: { _controller: KidsFrontBundle:Services:ajoutrendezvous}
afficherServicejson:
    path:     /afficherServicejson
    defaults: { _controller: KidsFrontBundle:Services:afficherServicejsonFront}