kids_backend:
    resource: "@KidsBackendBundle/Resources/config/routing.yml"
    prefix:   /back

kids_front:
    resource: "@KidsFrontBundle/Resources/config/routing.yml"
    prefix:   /front

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

ancarebeca_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yml"