<?php

namespace UserBundle\Repository;

/**
 * ActiviteEnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteEnfantRepository extends \Doctrine\ORM\EntityRepository
{
}
