<?php

namespace UserBundle\Repository;

/**
 * AffectinClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffectinClubRepository extends \Doctrine\ORM\EntityRepository
{
}
