<?php

namespace UserBundle\Repository;

/**
 * CategoriePublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriePublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
