<?php

namespace UserBundle\Repository;

/**
 * categforumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categforumRepository extends \Doctrine\ORM\EntityRepository
{
}
