<?php

namespace UserBundle\Repository;

/**
 * EnfantsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfantsRepository extends \Doctrine\ORM\EntityRepository
{
}
