<?php

namespace UserBundle\Repository;

/**
 * EventCustomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCustomRepository extends \Doctrine\ORM\EntityRepository
{
}
