<?php

namespace UserBundle\Repository;

/**
 * ProfilEnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilEnfantRepository extends \Doctrine\ORM\EntityRepository
{
}
