<?php

namespace UserBundle\Repository;

/**
 * TypeServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
