<?php

namespace UserBundle\Repository;

/**
 * TypePublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypePublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
