<?php

namespace UserBundle\Repository;

/**
 * UserEtablissementVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEtablissementVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
