<?php

namespace UserBundle\Repository;

/**
 * UserEtablissementFavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserEtablissementFavorisRepository extends \Doctrine\ORM\EntityRepository
{
}
