kids_backend_homepage:
    path:     /espaceAdmin
    defaults: { _controller: KidsBackendBundle:Admin:admin }

afficherAllEtablissement:
    path: /afficherAllEtablissement
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:afficherAllEtablissement}

afficherEtablissementbyid:
    path: /afficherEtablissementbyid/id/{id}
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:afficherEtablissementbyid}

afficheretablissementparsearch:
    path: /afficheretablissementparsearch
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:afficheretablissementparsearch}
afficherAllEnseignant:
    path: /afficherAllEnseignant
    defaults: { _controller: KidsBackendBundle:AdminEnseignants:afficherAllEnseignant}
afficherEnseignantparid:
    path: /afficherEnseignantparid/id/{id}
    defaults: { _controller: KidsBackendBundle:AdminEnseignants:afficherEnseignantbyid}

afficherAllGallerie:
    path: /afficherAllGallerie
    defaults: { _controller: KidsBackendBundle:AdminGallerie:afficherAllGallerie}
afficherGallerieByEtab:
    path: /afficherGallerieByEtab
    defaults: { _controller: KidsBackendBundle:AdminGallerie:afficherGallerieByEtab}

notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    type: annotation
send_notification:
    path: /send-notification
    defaults: { _controller: KidsBackendBundle:Admin:sendNotification}

getNotificationsAction:
    path: /getNotifications
    defaults: { _controller: KidsBackendBundle:Admin:getNotifications}

cree_Pub:
    path: /creerpub
    defaults : {_controller: KidsBackendBundle:Publication:creerpub }

creertype_Pub:
    path: /creertypepub
    defaults : {_controller: KidsBackendBundle:Publication:creertypepub }

supprimertype_pubparid:
    path: /supprimertypepubparid/{id}
    defaults : {_controller: KidsBackendBundle:Publication:supprimertypepubparid }

supprimercategorie_parid:
    path: /supprimercategorieparid/{id}
    defaults : {_controller: KidsBackendBundle:Publication:supprimercategorieparid }

creercategorie_Pub:
    path: /creercatpub
    defaults : {_controller: KidsBackendBundle:Publication:creercategoriepub }

afficher_pub:
    path: /afficherpub
    defaults : {_controller: KidsBackendBundle:Publication:afficherpub }

supprimer_pubparid:
    path: /supprimerpubparid/{id}
    defaults : {_controller: KidsBackendBundle:Publication:supprimerpubparid }

modifier_pubparid:
    path: /modifierpubparid/{id}
    defaults : {_controller: KidsBackendBundle:Publication:modifierpubparid }

recherchePub_Titre:
    path: /recherchePubTitre
    defaults : {_controller: KidsBackendBundle:Publication:recherchePubTitre}
test:
    path:     /test
    defaults: { _controller: KidsBackendBundle:Default:test }

ajout:
    path:     /ajout
    defaults: { _controller: KidsBackendBundle:Service:ajout }

afficherServiceBack:
    path:     /afficherServiceBack
    defaults: { _controller: KidsBackendBundle:Service:afficherServiceBack}

updateService:
    path:     /updateService/{id}
    defaults: { _controller: KidsBackendBundle:Service:updateService }

suppServ:
    path:     /suppServ/{id}
    defaults: { _controller: KidsBackendBundle:Service:suppServ }
rechercheback:
    path:     /rechercheback}
    defaults: { _controller: KidsBackendBundle:Service:rechercheback }
