kids_backend_homepage:
    path:     /admintemplate
    defaults: { _controller: KidsBackendBundle:Default:admin }
listeclub:
    path:     /listeclub
    defaults: { _controller: KidsBackendBundle:Club:listeclub }
calendrierClub:
    path:     /calendrierClub
    defaults: { _controller: KidsBackendBundle:Club:calendrierClub }
ajouterevntClub:
    path:     /ajouterevntClub
    defaults: { _controller: KidsBackendBundle:Club:ajouterevntClub }
ajouterClub:
    path:     /ajouterClub
    defaults: { _controller: KidsBackendBundle:Club:ajouterClub }
afficherClub:
    path:     /afficherClub
    defaults: { _controller: KidsBackendBundle:Club:afficherClub }
modificationClub:
    path:     /modificationClub/{id}
    defaults: { _controller: KidsBackendBundle:Club:modificationClub }
remove:
    path:     /remove/{id}
    defaults: { _controller: KidsBackendBundle:Club:remove }
search:
    path:     /search
    defaults: { _controller: KidsBackendBundle:Club:search}

afficheEvntCostom:
    path:     /afficheEvntCostom
    defaults: { _controller: KidsBackendBundle:Club:afficheEvntCostom}
ajouterEvntCalendarClub:
    path:     /ajouterEvntCalendarClub
    defaults: { _controller: KidsBackendBundle:Club:ajouterEvntCalendarClub }
modifierCalendar:
    path:     /modifierCalendar/{id}
    defaults: { _controller: KidsBackendBundle:Club:modifierCalendar }
supprimerEvntCalendar:
    path:     /supprimerEvntCalendar/{id}
    defaults: { _controller: KidsBackendBundle:Club:supprimerEvntCalendar}