kids_backend_homepage:
    path:     /espaceAdmin
    defaults: { _controller: KidsBackendBundle:Admin:admin }

afficherAllEtablissement:
    path: /afficherAllEtablissement
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:afficherAllEtablissement}
accepterEtablissement:
    path: /accepterEtablissement/{id}
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:accepterEtablissement}

refuserEtablissement:
    path: /refuserEtablissement/{id}
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:refuserEtablissement}

afficherINPEtablissement:
    path: /afficherINPEtablissement
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:afficherINPEtablissement}

afficherEtablissementbyid:
    path: /afficherEtablissementbyid/id/{id}
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:afficherEtablissementbyid}

afficheretablissementparsearch:
    path: /afficheretablissementparsearch
    defaults: { _controller: KidsBackendBundle:AdminEtablissement:afficheretablissementparsearch}
afficherAllEnseignant:
    path: /afficherAllEnseignant
    defaults: { _controller: KidsBackendBundle:AdminEnseignants:afficherAllEnseignant}
afficherEnseignantparid:
    path: /afficherEnseignantparid/id/{id}
    defaults: { _controller: KidsBackendBundle:AdminEnseignants:afficherEnseignantbyid}

afficherAllGallerie:
    path: /afficherAllGallerie
    defaults: { _controller: KidsBackendBundle:AdminGallerie:afficherAllGallerie}
afficherGallerieByEtab:
    path: /afficherGallerieByEtab
    defaults: { _controller: KidsBackendBundle:AdminGallerie:afficherGallerieByEtab}


notifications:
    resource: "@MgiletNotificationBundle/Controller/"
    type: annotation
send_notification:
    path: /send-notification
    defaults: { _controller: KidsBackendBundle:Admin:sendNotification}

getNotificationsAction:
    path: /getNotifications
    defaults: { _controller: KidsBackendBundle:Admin:getNotifications}

cree_Pub:
    path: /creerpub
    defaults : {_controller: KidsBackendBundle:Publication:creerpub }

creertype_Pub:
    path: /creertypepub
    defaults : {_controller: KidsBackendBundle:Publication:creertypepub }

supprimertype_pubparid:
    path: /supprimertypepubparid/{id}
    defaults : {_controller: KidsBackendBundle:Publication:supprimertypepubparid }

supprimercategorie_parid:
    path: /supprimercategorieparid/{id}
    defaults : {_controller: KidsBackendBundle:Publication:supprimercategorieparid }

creercategorie_Pub:
    path: /creercatpub
    defaults : {_controller: KidsBackendBundle:Publication:creercategoriepub }

afficher_pub:
    path: /afficherpub
    defaults : {_controller: KidsBackendBundle:Publication:afficherpub }

supprimer_pubparid:
    path: /supprimerpubparid/{id}
    defaults : {_controller: KidsBackendBundle:Publication:supprimerpubparid }

modifier_pubparid:
    path: /modifierpubparid/{id}
    defaults : {_controller: KidsBackendBundle:Publication:modifierpubparid }

recherchePub_Titre:
    path: /recherchePubTitre
    defaults : {_controller: KidsBackendBundle:Publication:recherchePubTitre}

ajout:
    path:     /ajout
    defaults: { _controller: KidsBackendBundle:Service:ajout }

afficherServiceBack:
    path:     /afficherServiceBack
    defaults: { _controller: KidsBackendBundle:Service:afficherServiceBack}

updateService:
    path:     /updateService/{id}
    defaults: { _controller: KidsBackendBundle:Service:updateService }

suppServ:
    path:     /suppServ/{id}
    defaults: { _controller: KidsBackendBundle:Service:suppServ }
rechercheback:
    path:     /rechercheback}
    defaults: { _controller: KidsBackendBundle:Service:rechercheback }

ajouterProduit:
    path:     /ajouterProduit
    defaults: { _controller: KidsBackendBundle:Produits:ajouterProduit}
afficherProduit:
    path:     /afficherProduit
    defaults: { _controller: KidsBackendBundle:Produits:afficherProduit}
supprimerProduit:
    path:     /supprimerProduit/{id}
    defaults: { _controller: KidsBackendBundle:Produits:supprimerProduit}
ajouterCateg:
    path:     /ajouterCateg
    defaults: { _controller: KidsBackendBundle:Produits:ajouterCateg}
afficherCateg:
    path:    /afficherCateg
    defaults: { _controller: KidsBackendBundle:Produits:afficherCateg}
rechercherProduit:
    path:    /rechercherProduit
    defaults:  { _controller: KidsBackendBundle:Produits:rechercherProduit}
modifierProduit:
    path:    /modifierProduit/{id}
    defaults:  { _controller: KidsBackendBundle:Produits:modifierProduit}
stat:
    path:     /stat
    defaults: { _controller: KidsBackendBundle:Produits:stat}
listeclub:
    path:     /listeclub
    defaults: { _controller: KidsBackendBundle:Club:listeclub }
calendrierClub:
    path:     /calendrierClub
    defaults: { _controller: KidsBackendBundle:Club:calendrierClub }
ajouterevntClub:
    path:     /ajouterevntClub
    defaults: { _controller: KidsBackendBundle:Club:ajouterevntClub }
ajouterClub:
    path:     /ajouterClub
    defaults: { _controller: KidsBackendBundle:Club:ajouterClub }
afficherClub:
    path:     /afficherClub
    defaults: { _controller: KidsBackendBundle:Club:afficherClub }
modificationClub:
    path:     /modificationClub/{id}
    defaults: { _controller: KidsBackendBundle:Club:modificationClub }
remove:
    path:     /remove/{id}
    defaults: { _controller: KidsBackendBundle:Club:remove }
search:
    path:     /search
    defaults: { _controller: KidsBackendBundle:Club:search}

afficheEvntCostom:
    path:     /afficheEvntCostom
    defaults: { _controller: KidsBackendBundle:Club:afficheEvntCostom}
ajouterEvntCalendarClub:
    path:     /ajouterEvntCalendarClub
    defaults: { _controller: KidsBackendBundle:Club:ajouterEvntCalendarClub }
modifierCalendar:
    path:     /modifierCalendar/{id}
    defaults: { _controller: KidsBackendBundle:Club:modifierCalendar }
supprimerEvntCalendar:
    path:     /supprimerEvntCalendar/{id}
    defaults: { _controller: KidsBackendBundle:Club:supprimerEvntCalendar}
afficherClubJson:
    path:     /afficherClubJson
    defaults: { _controller: KidsBackendBundle:Club:afficherClubJson}
afficherClubJsonbyId:
    path:     /afficherClubJsonbyId/{id}
    defaults: { _controller: KidsBackendBundle:Club:afficherClubJsonbyId}
deleteClubJson:
    path:     /deleteClubJson/{id}
    defaults: { _controller: KidsBackendBundle:Club:deleteClubJson}
ajouterClubJson:
    path:     /ajouterClubJson
    defaults: { _controller: KidsBackendBundle:Club:ajouterClubJson}
searchJson:
    path:     /searchJson/{nom}
    defaults: { _controller: KidsBackendBundle:Club:searchJson}

